application: beepbox-synth
version: 1-1
runtime: python
api_version: 1

handlers:

- url: /BeepBoxOnline\.swf
  static_files: BeepBoxOnline.swf
  upload: BeepBoxOnline\.swf

- url: /BeepBoxOffline\.swf
  static_files: BeepBoxOffline.swf
  upload: BeepBoxOffline\.swf

- url: /BeepBoxEmbedded\.swf
  static_files: BeepBoxEmbedded.swf
  upload: BeepBoxEmbedded\.swf

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /
  static_files: index.html
  upload: index\.html

- url: /embed\.html
  static_files: embed.html
  upload: embed\.html

- url: /test\.html
  static_files: test.html
  upload: test\.html

- url: .*
  script: main.py
